# Generated by Django 5.2 on 2025-06-01 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='holdings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
