# Generated by Django 5.2 on 2025-06-02 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio_holdings_alter_portfolio_cash_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.FloatField(default=100000.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
