# Generated by Django 5.2 on 2025-06-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_portfolio_cash_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fx_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_executed',
            field=models.FloatField(),
        ),
    ]
