# Generated by Django 5.2 on 2025-06-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_order_fx_rate_alter_order_price_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD'),
        ),
    ]
