# Generated by Django 5.2.5 on 2025-08-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0009_alter_portfolio_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="substack_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
