# Generated by Django 5.2.5 on 2025-08-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0010_portfolio_substack_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
