# Generated by Django 5.2.5 on 2025-08-31 14:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0011_portfolio_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fx_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_executed",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="cash_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100000.00"),
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosnapshot",
            name="total_value",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
