# Generated by Django 5.2.5 on 2025-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0012_alter_order_fx_rate_alter_order_price_executed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="short_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
