# Generated by Django 5.2.5 on 2025-09-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0015_portfoliofollower"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioAllowedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_emails",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "email")},
            },
        ),
    ]
