# Generated by Django 5.2.5 on 2025-09-02 02:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0016_portfolioallowedemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fx_rate",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("1.0"), max_digits=20
            ),
        ),
    ]
