# Generated by Django 5.2 on 2025-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_alter_order_fx_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url_tag',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
