# Generated by Django 5.2 on 2025-12-19 19:37

from django.db import migrations
from django.utils.text import slugify
from urllib.parse import urlparse


def derive_url_tag(substack_url: str):
    parsed = urlparse(substack_url)
    host = (parsed.hostname or "").lower()
    if host.endswith(".substack.com"):
        return slugify(host.rsplit(".substack.com", 1)[0])
    if host in {"substack.com", "www.substack.com"}:
        path = parsed.path.strip("/")
        if path:
            return slugify(path.lstrip("@"))
    return None


def populate_url_tags(apps, schema_editor):
    Portfolio = apps.get_model("portfolios", "Portfolio")
    for portfolio in Portfolio.objects.filter(url_tag__isnull=True).exclude(substack_url__isnull=True).exclude(substack_url=""):
        tag = derive_url_tag(portfolio.substack_url)
        if tag:
            portfolio.url_tag = tag
            portfolio.save(update_fields=["url_tag"])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0018_portfolio_url_tag'),
    ]

    operations = [
        migrations.RunPython(populate_url_tags, migrations.RunPython.noop),
    ]
