# Generated by Django 5.2.5 on 2024-01-01 00:00

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def populate_url_tags(apps, schema_editor):
    Portfolio = apps.get_model("portfolios", "Portfolio")
    for portfolio in Portfolio.objects.all():
        if portfolio.url_tag:
            continue
        base = slugify(portfolio.name) or slugify(portfolio.user.username) or "portfolio"
        candidate = base or "portfolio"
        while Portfolio.objects.filter(url_tag=candidate).exclude(pk=portfolio.pk).exists():
            candidate = f"{base}-{uuid.uuid4().hex[:6]}"
        portfolio.url_tag = candidate
        portfolio.save(update_fields=["url_tag"])


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0018_notificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="url_tag",
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.RunPython(populate_url_tags, migrations.RunPython.noop),
    ]
