# Generated by Django 5.2 on 2025-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0019_portfolio_url_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
