# Generated by Django 5.2.7 on 2025-10-23 12:45

from django.db import migrations

from announcements.constants import DEFAULT_ANNOUNCEMENT_TYPES


def create_default_types(apps, schema_editor):
    AnnouncementType = apps.get_model("announcements", "AnnouncementType")
    for record in DEFAULT_ANNOUNCEMENT_TYPES:
        AnnouncementType.objects.update_or_create(
            code=record["code"],
            defaults={
                "label": record["label"],
                "description": record["description"],
                "default_is_important": record["default_is_important"],
            },
        )


def remove_default_types(apps, schema_editor):
    AnnouncementType = apps.get_model("announcements", "AnnouncementType")
    codes = [record["code"] for record in DEFAULT_ANNOUNCEMENT_TYPES]
    AnnouncementType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_types, remove_default_types),
    ]
